In [68]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

url = "https://hijri-calendar.com/Rabiulakhir/1442"
url = "https://hijri-calendar.com/Jamadilawal/1442"
response = requests.get(url)
soup = BeautifulSoup(response.text, "lxml")
Hijri = []
Melady =[]
cols = ['HijryDate','MeladyDate']

In [69]:
for  el in soup.find_all(class_='hijri'):
    Hijri.append(el.text)

skip = 0 
el_list = soup.find_all(class_='meladi')
for el in range(1,len(el_list),2):
    Melady.append(el_list[el].text)
    #print(el_list[el])
    
assert len(Melady) == len(Hijri)
#print(list(zip(Hijri,Melady)))
list(zip(Hijri,Melady))
df = pd.DataFrame(columns=cols,data=list(zip(Hijri,Melady)))
df

    HijryDate  MeladyDate
0   1442/4/27  2020/12/12
1   1442/4/28  2020/12/13
2   1442/4/29  2020/12/14
3   1442/4/30  2020/12/15
4    1442/5/1  2020/12/16
5    1442/5/2  2020/12/17
6    1442/5/3  2020/12/18
7    1442/5/4  2020/12/19
8    1442/5/5  2020/12/20
9    1442/5/6  2020/12/21
10   1442/5/7  2020/12/22
11   1442/5/8  2020/12/23
12   1442/5/9  2020/12/24
13  1442/5/10  2020/12/25
14  1442/5/11  2020/12/26
15  1442/5/12  2020/12/27
16  1442/5/13  2020/12/28
17  1442/5/14  2020/12/29
18  1442/5/15  2020/12/30
19  1442/5/16  2020/12/31
20  1442/5/17    2021/1/1
21  1442/5/18    2021/1/2
22  1442/5/19    2021/1/3
23  1442/5/20    2021/1/4
24  1442/5/21    2021/1/5
25  1442/5/22    2021/1/6
26  1442/5/23    2021/1/7
27  1442/5/24    2021/1/8
28  1442/5/25    2021/1/9
29  1442/5/26   2021/1/10
30  1442/5/27   2021/1/11
31  1442/5/28   2021/1/12
32  1442/5/29   2021/1/13
33   1442/6/1   2021/1/14
34   1442/6/2   2021/1/15

In [83]:
df["Date"] = pd.to_datetime(df['MeladyDate'])
df["AD_Year"] = df["Date"].dt.year
df["AD_Month"] = df["Date"].dt.month
df["AD_Day"] = df["Date"].dt.day

df[['AH_Year','AH_Month','AH_Day']] = (df['HijryDate'].str.split('/',expand=True)).astype('int')

In [81]:
Hijry_Months = ['Rabiulawal','Safar','Muharam','Zulhijah','Zulkaedah','Syawal','Ramadan','Syaaban','Rejab','Jamadilakhir','Jamadilawal','Rabiulakhir']

12